# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy the entire repository
COPY . .

# Build the liblab package from the repository root
RUN npm install --ignore-scripts && npm run build

# Build the MCP server
WORKDIR /app/mcp
RUN npm install --ignore-scripts && npm run build

EXPOSE 8080

CMD ["node", "dist/index.js"]
