# wrangler.toml configuration file for Cloudflare Workers
name = "test"
main = "worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-04-08"

# Configure your account ID and zone ID
# account_id = "your-cloudflare-account-id"
# zone_id = "your-cloudflare-zone-id"

# Routes configuration
# routes = [
#   { pattern = "example.com/*", zone_id = "your-cloudflare-zone-id" }
# ]